enum NodeType { 
    SOURCE, 
    LOGISTICS,
    CORNERLOG_DOWNIN_RIGHTOUT,
    CORNERLOG_DOWNIN_LEFTOUT,
    CORNERLOG_UPIN_RIGHTOUT,
    CORNERLOG_UPIN_LEFTOUT,
    MERGE, 
    RECEIVER,
    DUPLICATOR
};